name = "norwind"
description = "A blog theme using Tailwind CSS for zola"
license = "MIT"
homepage = "https://github.com/nobodygx/norwind"
min_version = "0.1.1"

[extra]

[author]
name = "NObodyGX"
homepage = "https://github.com/nobodygx"
